name: MySQL Action

on:
  workflow_dispatch:

jobs:
  mysql-job:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 1234
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u root -p1234"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Show databases
        run: mysql -h 127.0.0.1 -u root -p1234 -e "SHOW DATABASES;"