name: MySQL Action

on: push

jobs:
  mysql-job:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: 123

    steps:
      - name: Show databases
        run: mysql -h 127.0.0.1 -u root -p123 -e "SHOW DATABASES;"